##############################################################
# Learning Module: Vagrant Up for Network Envineers
# Lab: Using the Ansible Provisioner with Vagrant
# Author: Hank Preston <hapresto@cisco.com>
#
# ansible_provision.yaml
# Illustrate the following concepts:
# - Basic Playbook Structure for NX-OS Modules
# - Customizations to support Vagrant Devices
##############################################################
---
- name: Provision NX-OS Devices
  hosts: vagrant
  connection: ansible.netcommon.httpapi
  gather_facts: false

  tasks:
    - name: Pause to complete boot
      pause:
        seconds: 5

    - name: Enable NX-API
      nxos_feature:
        feature: nxapi
        state: enabled
      connection: ansible.netcommon.network_cli

    # This is required as more recent images seem to default to HTTPS only.

    - name: Configure nxapi to use http
      cisco.nxos.nxos_nxapi:
        http: yes
        http_port: 80
      connection: ansible.netcommon.network_cli

    - name: Configure System Settings
      nxos_system:
        hostname: "{{ inventory_hostname }}"

    - name: Configure Interfaces
      with_items: "{{ interfaces }}"
      nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: layer3
            description: "{{ item.desc }}"
            enabled: true
      when: "'oopback' not in item.name"

    - name: Configure Loopback Interfaces
      with_items: "{{ interfaces }}"
      nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: true
      when: "'oopback' in item.name"

    - name: Configure IPv4 Address on Interface
      with_items: "{{ interfaces }}"
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip_address }}/{{ item.prefix }}"


