---
# Modern ansible doesn't use provider.

ansible_network_os: nxos
ansible_host: 127.0.0.1
ansible_port: 2222
ansible_user: vagrant
ansible_password: vagrant
ansible_httpapi_port: 2224

interfaces:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.21.1.1
      prefix: 24
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.21.2.1
      prefix: 24
    - name: Loopback13
      desc: Sample Network Route Injection
      ip_address: 172.21.3.1
      prefix: 24
    - name: Loopback14
      desc: Sample Network Route Injection
      ip_address: 172.21.4.1
      prefix: 24
    - name: Ethernet1/1
      desc: Link to other switch
      ip_address: 172.20.0.1
      prefix: 24
